import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import AllProviders from "@/providers/allProviders";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
       title: "Create Next App",
       description: "Generated by create next app",
};

export default function RootLayout({
       children,
}: Readonly<{
       children: React.ReactNode;
}>) {
       return (
              <html lang="en" suppressHydrationWarning>
                     <body className={inter.className}>
                            <AllProviders>{children}</AllProviders>
                            <ToastContainer />
                     </body>
              </html>
       );
}
